default_language_version:
  python: python3.10
  node: 16.14.2

ci:
  skip: [generate-schemas]

repos:
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        name: Blacken
        args: ["--config", "pyproject.toml"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: (pydatalab/example_data/)|(.*.snap)
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: end-of-file-fixer
        exclude: ^(pydatalab/example_data/|pydatalab/schemas)
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-symlinks
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.1.4"
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [javascript, jsx, vue, html, yaml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-all", "pydantic~=1.10"]

  - repo: local
    hooks:
      - id: generate-schemas
        name: Regenerate item model JSONSchemas
        description: Check if the current code changes have enacted changes to the resulting JSONSchemas
        entry: invoke -r pydatalab dev.generate-schemas
        pass_filenames: false
        language: python
