default_language_version:
  python: python3.10
  node: "20.17.0"

ci:
  skip:
    # skip generate-schemas as pre-commit-ci will not have correct environment
    - generate-schemas
  autoupdate_schedule: "monthly"
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: (pydatalab/example_data/)|(.*.snap)
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: end-of-file-fixer
        exclude: ^(pydatalab/example_data/|pydatalab/schemas)
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-symlinks
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/oxc-project/mirrors-oxlint
    rev: v1.41.0
    hooks:
      - id: oxlint

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.0
    hooks:
      - id: mypy
        additional_dependencies:
          ["types-python-dateutil", "types-requests", "types-paramiko", "pydantic~=1.10"]
        args: ["--config-file", "pydatalab/pyproject.toml"]

  - repo: local
    hooks:
      - id: generate-schemas
        name: Regenerate item model JSONSchemas
        files: "^pydatalab/src/pydatalab/models/.*.$"
        description: Check if the current code changes have enacted changes to the resulting JSONSchemas
        entry: invoke -r pydatalab dev.generate-schemas
        pass_filenames: false
        language: system
